### ISSUE TITLE
no way to copy converted text (MacOS, GUI version)

### ISSUE THREAD

**Issue by abunur** [BlackDragonBE/MarkdownToRW_Converter#6] opened 2018-11-20 21:59 UTC
There's no apparent way to copy the converted text out of the app.  Command-C doesn't work, right-clicking just unselects the text, and there is no export feature that doesn't cause an application crash instead.

**Comment by BlackDragonBE** [comment] 2018-11-21 09:42
Duplicate of #3

**Closed as completed by BlackDragonBE** 2018-11-21 09:42 UTC
